version: '3.8'

services:
  rust:
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
    tty: true
    working_dir: /workspace
    ports:
      - 8080:8080
    volumes:
      - .:/workspace
      - rust-target:/workspace/target
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: rust_sql
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/mysqlvol:/var/lib/mysql

volumes:
  rust-target:
